= DcDccNanoControler extension Library for Arduino =

This library is made to build Basic Dcc controler on small Arduinos Nano or Uno.

For more information about this library please visit us at
http://www.locoduino.org/spip.php?article224 in french or
http://git.framasoft.org/locoduino.org/DcDccNanoControler/wikis/home for both french and english.

== License ==

Copyright (c) 2017 Locoduino.org. All right reserved.
Copyright (c) 2017 Thierry Paris. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA